import { requireUser } from '@/server/auth';
import { studentData } from '@/server/repository';
import { WorkspaceNav } from '@/components/layout/workspace-nav';
import { BadgeCard, DashboardMetric, ProgressRing, SkillBars, StatusBadge } from '@/components/ui/primitives';
import { formatDateOnly } from '@/lib/formatters';

export default async function PortfolioPage() {
  const user = await requireUser(['student']); const { database, profile, applications, unlocked, reports } = await studentData(user.id); const completed = applications.filter((item) => item.status === 'attended'); const accepted = reports.filter((item) => item.status === 'approved'); const skills = Array.from(new Set([...completed.flatMap((item) => item.activity.skills), ...accepted.flatMap((item) => item.skillsGained.split(',').map((skill) => skill.trim()).filter(Boolean))])).slice(0, 8); const badgeImage = (imageKey: number) => database.mediaAssets.find((item) => item.kind === 'badge' && item.imageKey === imageKey)?.url;
  return <div className="page"><div className="workspace"><WorkspaceNav role="student" active="/student/portfolio" /><div className="workspace-main"><section className="portfolio-head route-portfolio"><div><p className="eyebrow">Цифрове портфоліо</p><h1>{profile.fullName}</h1><p>Карта компетентностей, підтверджені докази та відкриті відзнаки.</p></div><ProgressRing value={Math.min(100, profile.pointsTotal)} label="бали" /></section><div className="dashboard-grid" style={{ marginTop: 18 }}><DashboardMetric label="Бали" value={profile.pointsTotal} accent="aqua" /><DashboardMetric label="Підтверджені кроки" value={completed.length} accent="lime" /><DashboardMetric label="Прийняті докази" value={accepted.length} accent="violet" /><DashboardMetric label="Відзнаки" value={unlocked.length} accent="coral" /></div><div className="dashboard-columns"><section className="surface"><div className="surface-head"><h2>Карта компетентностей</h2><button className="button button-secondary" type="button" onClick={() => undefined}>Друк</button></div>{skills.length ? <SkillBars skills={skills} /> : <p>Підтверджені компетентності з’являться після прийнятих доказів.</p>}<div className="row-list">{completed.map((item) => <div className="queue-row" key={item.id}><div><b>{item.activity.title}</b><small>{formatDateOnly(item.activity.startAt)} · {item.activity.category.name}</small></div><StatusBadge status="attended" /></div>)}</div></section><section className="surface"><div className="surface-head"><h2>Відкриті відзнаки</h2></div>{unlocked.length ? unlocked.map((item) => <BadgeCard badge={item.badge} unlockedAt={item.unlockedAt} imageUrl={badgeImage(item.badge.imageKey)} key={item.id} />) : <p>Поки що немає відзнак.</p>}</section></div></div></div></div>;
}
